version: "3.6"
services:
  entry:
    build: ./entry
    restart: unless-stopped
    ports:
      - "30080:80"

  database:
    build: ./database
    restart: unless-stopped
    ports:
      - "33306:80"
    volumes:
      - ${PWD}/database/db.json:/root/db.json
    networks:
      - auth-sharing-net

  query-session:
    build: ./query-session
    restart: unless-stopped
    ports:
      - "30180:80"
    networks:
      - auth-sharing-net

  cookie-session:
    build: ./cookie-session
    restart: unless-stopped
    ports:
      - "30280:80"
    networks:
      - auth-sharing-net

  common-session:
    build: ./common-session
    restart: unless-stopped
    ports:
      - "30380:80"
    networks:
      - auth-sharing-net

  http-auth-session:
    build: ./http-auth-session
    restart: unless-stopped
    ports:
      - "30480:80"
    networks:
      - auth-sharing-net

  jwt-session:
    build: ./jwt-session
    restart: unless-stopped
    volumes:
      - ${PWD}/jwtRS256.key:/root/jwtRS256.key
      - ${PWD}/jwtRS256.key.pub:/root/jwtRS256.key.pub
    environment:
      - RESOURCE_SERVER=http://localhost:30680
    ports:
      - "30580:80"
    networks:
      - auth-sharing-net

  resource:
    build: ./resource
    restart: unless-stopped
    volumes:
      - ${PWD}/jwtRS256.key.pub:/root/jwtRS256.key.pub
    ports:
      - "30680:80"

networks:
  auth-sharing-net:
