version: "3.6"
services:
  entry:
    build: ./entry
    restart: unless-stopped
    ports:
      - "10080:80"

  database:
    build: ./database
    restart: unless-stopped
    ports:
      - "13306:80"
    volumes:
      - ${PWD}/database/db.json:/root/db.json
    networks:
      - auth-sharing-net

  query-session:
    build: ./query-session
    restart: unless-stopped
    ports:
      - "10180:80"
    networks:
      - auth-sharing-net

networks:
  auth-sharing-net:
